### ISSUE TITLE
Final Scene Bugs

### ISSUE THREAD

**Issue by alexdea123** [YehorK/Whispers-of-the-Fountain-VR#13]
Address the bugs with Ogopogo rising too early before all 4 children are thrown in.

**Comment by ykarpi** [comment]
also after the talk is done, it goes up, but stops at certain height. I think it makes sense to make set it to inactive or destroy the game object.
![image](https://github.com/user-attachments/assets/b2d4fa32-fb18-49b5-bf67-23888b6be9b4)
