### ISSUE TITLE
Journals around the scene

### ISSUE THREAD

**Issue by ykarpi** [YehorK/Whispers-of-the-Fountain-VR#19]
The journals with the cues stay active in the scene for the whole runtime. Can we (should we?) manage it somehow?

**Comment by alexdea123** [comment]
Wait really?? They should be deactivating as soon as the next fragment is found. This was tested by me previously, unless we are talking about different issues.

**Comment by ykarpi** [comment]
Only the journals that appear after the collection of every fragment stay
in the scene. The other couple appearances of the journal that guide the
player to the 1st fragment disappear timely.

I can have a look tomorrow.

**Comment by ykarpi** [comment]
fixed in the latest PR #21
