### ISSUE TITLE
Fragments collection

### ISSUE THREAD

**Issue by ykarpi** [YehorK/Whispers-of-the-Fountain-VR#8]
- Add sounds to when hte fragments are collected.
- add functionality to grab the fragment (but then should it just disappear from your hand?)

**Comment by alexdea123** [comment]
I added sounds to the mini green shards. The main fragments should have sounds, but they aren't working for some reason. I also am stumped on how to make them grabbable, i made them XR Grab interactible but they are NOT working at all to be grabbed. I even changed their script to do the collection and disappearing upon the grab, but it doesn't want to detect it at all.

**Comment by ykarpi** [comment]
fragment sounds working in #16 . The issue was that the fragment object would be turned inactive before the audio plays. Now, with the delay it seems to work fine. So the logic is: detect the player --> play the collection audio + turn the crystal's renderer off (these two basically happen simuteniously) --> when the audio is played make this Fragment interaction objects inactive (managed by the Fragment Collection Manager)

**Comment by ykarpi** [comment]
As for grabbing - my suggestion is to leave things as it is (i.e. without grabbing, but just detect colider collisions with the Player - it seems to work pretty well). The reasons why grabbale is not working could be different - the fragment is moving in space up & down. Also, we would have to refactor some code for activating different parts of the game to work with grabbing instead of player's tag detection.

**Comment by ykarpi** [comment]
grabbing is not implemented. Otherwise, sound-related stuff is fixed in #16
